### ISSUE TITLE
Can't build on windows

### ISSUE THREAD

**Issue by andruhon** [dherman/wc-demo#5]
Can't build native part of the wc-demo with "The filename or extension is too long. (os error 206)" error

I've tried to fix that with moving multirust from ~, but there are some more files deeper.

```
unable to get packages from source

Caused by:
  failed to unpack package `neon-sys v0.1.7`

Caused by:
  failed to create `C:/multirust/toolchains/stable/cargo\registry\src\github.com-88ac128001ac3a9a\neon-sys-0.1.7\node_modules\node-gyp\node_modules\request\node_modules\har-validator\node_modules\is-my-json-alid\node_modules\generate-object-property\node_modules\is-property`

Caused by:
  The filename or extension is too long. (os error 206)
```

**Comment by andruhon** [comment]
More detailed output for freshly cloned thing

```
C:\local_projects\rust>git clone https://github.com/dherman/wc-demo.git
Cloning into 'wc-demo'...
remote: Counting objects: 74, done.
remote: Total 74 (delta 0), reused 0 (delta 0), pack-reused 74
Unpacking objects: 100% (74/74), done.
Checking connectivity... done.

C:\local_projects\rust>cd wc-demo\native\

C:\local_projects\rust\wc-demo\native>cargo build --verbose
    Updating git repository `https://github.com/nikomatsakis/rayon`
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling winapi v0.2.5
     Running `rustc C:\multirust\cargo\registry\src\github.com-88ac128001ac3a9a\winapi-0.2.5\sr                                         c\lib.rs --crate-name winapi --crate-type lib -g -C metadata=96db160368c72f00 -C extra-filename                                         =-96db160368c72f00 --out-dir C:\local_projects\rust\wc-demo\native\target\debug\deps --emit=dep                                         -info,link -L dependency=C:\local_projects\rust\wc-demo\native\target\debug\deps -L dependency=                                         C:\local_projects\rust\wc-demo\native\target\debug\deps --cap-lints allow`
   Compiling winapi-build v0.1.1
     Running `rustc C:\multirust\cargo\registry\src\github.com-88ac128001ac3a9a\winapi-build-0.                                         1.1\src\lib.rs --crate-name build --crate-type lib -g -C metadata=7bc4b8a4c9d61577 -C extra-fil                                         ename=-7bc4b8a4c9d61577 --out-dir C:\local_projects\rust\wc-demo\native\target\debug\deps --emi                                         t=dep-info,link -L dependency=C:\local_projects\rust\wc-demo\native\target\debug\deps -L depend                                         ency=C:\local_projects\rust\wc-demo\native\target\debug\deps --cap-lints allow`
   Compiling libc v0.2.5
     Running `rustc C:\multirust\cargo\registry\src\github.com-88ac128001ac3a9a\libc-0.2.5\src\                                         lib.rs --crate-name libc --crate-type lib -g --cfg "feature=\"default\"" -C metadata=86e36839d9                                         b4ae2b -C extra-filename=-86e36839d9b4ae2b --out-dir C:\local_projects\rust\wc-demo\native\targ                                         et\debug\deps --emit=dep-info,link -L dependency=C:\local_projects\rust\wc-demo\native\target\d                                         ebug\deps -L dependency=C:\local_projects\rust\wc-demo\native\target\debug\deps --cap-lints all                                         ow`
   Compiling advapi32-sys v0.1.2
     Running `rustc C:\multirust\cargo\registry\src\github.com-88ac128001ac3a9a\advapi32-sys-0.                                         1.2\build.rs --crate-name build_script_build --crate-type bin -g --out-dir C:\local_projects\ru                                         st\wc-demo\native\target\debug\build\advapi32-sys-911258561df3b2a9 --emit=dep-info,link -L depe                                         ndency=C:\local_projects\rust\wc-demo\native\target\debug\deps -L dependency=C:\local_projects\                                         rust\wc-demo\native\target\debug\deps --extern build=C:\local_projects\rust\wc-demo\native\targ                                         et\debug\deps\libbuild-7bc4b8a4c9d61577.rlib --cap-lints allow`
   Compiling kernel32-sys v0.2.1
     Running `rustc C:\multirust\cargo\registry\src\github.com-88ac128001ac3a9a\kernel32-sys-0.                                         2.1\build.rs --crate-name build_script_build --crate-type bin -g --out-dir C:\local_projects\ru                                         st\wc-demo\native\target\debug\build\kernel32-sys-a6ecb7771eb9fd8d --emit=dep-info,link -L depe                                         ndency=C:\local_projects\rust\wc-demo\native\target\debug\deps -L dependency=C:\local_projects\                                         rust\wc-demo\native\target\debug\deps --extern build=C:\local_projects\rust\wc-demo\native\targ                                         et\debug\deps\libbuild-7bc4b8a4c9d61577.rlib --cap-lints allow`
     Running `C:\local_projects\rust\wc-demo\native\target\debug\build\advapi32-sys-911258561df                                         3b2a9\build-script-build`
     Running `C:\local_projects\rust\wc-demo\native\target\debug\build\kernel32-sys-a6ecb7771eb                                         9fd8d\build-script-build`
C:\multirust\cargo\registry\src\github.com-88ac128001ac3a9a\winapi-0.2.5\src\lib.rs:4:21: 4:39 warning: lint raw_pointer_derive has been removed: using derive with raw pointers is ok
C:\multirust\cargo\registry\src\github.com-88ac128001ac3a9a\winapi-0.2.5\src\lib.rs:4 #![allow(bad_style, raw_pointer_derive)]
                                                                                                          ^~~~~~~~~~~~~~~~~~
     Running `rustc C:\multirust\cargo\registry\src\github.com-88ac128001ac3a9a\advapi32-sys-0.1.2\src\lib.rs --crate-name advapi32 --crate-type lib -g -C metadata=911258561df3b2a9 -C extra-filename=-911258561df3b2a9 --out-dir C:\local_projects\rust\wc-demo\native\target\debug\deps --emit=dep-info,link -L dependency=C:\local_projects\rust\wc-demo\native\target\debug\deps -L dependency=C:\local_projects\rust\wc-demo\native\target\debug\deps --extern winapi=C:\local_projects\rust\wc-demo\native\target\debug\deps\libwinapi-96db160368c72f00.rlib --cap-lints allow -l dylib=advapi32`
     Running `rustc C:\multirust\cargo\registry\src\github.com-88ac128001ac3a9a\kernel32-sys-0.2.1\src\lib.rs --crate-name kernel32 --crate-type lib -g -C metadata=a6ecb7771eb9fd8d -C extra-filename=-a6ecb7771eb9fd8d --out-dir C:\local_projects\rust\wc-demo\native\target\debug\deps --emit=dep-info,link -L dependency=C:\local_projects\rust\wc-demo\native\target\debug\deps -L dependency=C:\local_projects\rust\wc-demo\native\target\debug\deps --extern winapi=C:\local_projects\rust\wc-demo\native\target\debug\deps\libwinapi-96db160368c72f00.rlib --cap-lints allow -l dylib=kernel32`
   Compiling rand v0.3.13
     Running `rustc C:\multirust\cargo\registry\src\github.com-88ac128001ac3a9a\rand-0.3.13\src\lib.rs --crate-name rand --crate-type lib -g -C metadata=340832a8942cb900 -C extra-filename=-340832a8942cb900 --out-dir C:\local_projects\rust\wc-demo\native\target\debug\deps --emit=dep-info,link -L dependency=C:\local_projects\rust\wc-demo\native\target\debug\deps -L dependency=C:\local_projects\rust\wc-demo\native\target\debug\deps --extern advapi32=C:\local_projects\rust\wc-demo\native\target\debug\deps\libadvapi32-911258561df3b2a9.rlib --extern winapi=C:\local_projects\rust\wc-demo\native\target\debug\deps\libwinapi-96db160368c72f00.rlib --extern libc=C:\local_projects\rust\wc-demo\native\target\debug\deps\liblibc-86e36839d9b4ae2b.rlib --cap-lints allow`
   Compiling gcc v0.3.21
     Running `rustc C:\multirust\cargo\registry\src\github.com-88ac128001ac3a9a\gcc-0.3.21\src\lib.rs --crate-name gcc --crate-type lib -g -C metadata=35300ce5fd0fa3cd -C extra-filename=-35300ce5fd0fa3cd --out-dir C:\local_projects\rust\wc-demo\native\target\debug\deps --emit=dep-info,link -L dependency=C:\local_projects\rust\wc-demo\native\target\debug\deps -L dependency=C:\local_projects\rust\wc-demo\native\target\debug\deps --extern advapi32=C:\local_projects\rust\wc-demo\native\target\debug\deps\libadvapi32-911258561df3b2a9.rlib --extern winapi=C:\local_projects\rust\wc-demo\native\target\debug\deps\libwinapi-96db160368c72f00.rlib --cap-lints allow`
   Compiling num_cpus v0.2.10
     Running `rustc C:\multirust\cargo\registry\src\github.com-88ac128001ac3a9a\num_cpus-0.2.10\src\lib.rs --crate-name num_cpus --crate-type lib -g -C metadata=9a6b3f359403ec12 -C extra-filename=-9a6b3f359403ec12 --out-dir C:\local_projects\rust\wc-demo\native\target\debug\deps --emit=dep-info,link -L dependency=C:\local_projects\rust\wc-demo\native\target\debug\deps -L dependency=C:\local_projects\rust\wc-demo\native\target\debug\deps --extern winapi=C:\local_projects\rust\wc-demo\native\target\debug\deps\libwinapi-96db160368c72f00.rlib --extern libc=C:\local_projects\rust\wc-demo\native\target\debug\deps\liblibc-86e36839d9b4ae2b.rlib --extern kernel32=C:\local_projects\rust\wc-demo\native\target\debug\deps\libkernel32-a6ecb7771eb9fd8d.rlib --cap-lints allow`
   Compiling neon-sys v0.1.7
     Running `rustc C:\multirust\cargo\registry\src\github.com-88ac128001ac3a9a\neon-sys-0.1.7\build.rs --crate-name build_script_build --crate-type bin -g --out-dir C:\local_projects\rust\wc-demo\native\target\debug\build\neon-sys-51e0087a6aa7f0e4 --emit=dep-info,link -L dependency=C:\local_projects\rust\wc-demo\native\target\debug\deps -L dependency=C:\local_projects\rust\wc-demo\native\target\debug\deps --extern gcc=C:\local_projects\rust\wc-demo\native\target\debug\deps\libgcc-35300ce5fd0fa3cd.rlib --cap-lints allow`
     Running `C:\local_projects\rust\wc-demo\native\target\debug\build\neon-sys-51e0087a6aa7f0e4\build-script-build`
   Compiling deque v0.3.1
     Running `rustc C:\multirust\cargo\registry\src\github.com-88ac128001ac3a9a\deque-0.3.1\src\lib.rs --crate-name deque --crate-type lib -g -C metadata=401804ee703c3d62 -C extra-filename=-401804ee703c3d62 --out-dir C:\local_projects\rust\wc-demo\native\target\debug\deps --emit=dep-info,link -L dependency=C:\local_projects\rust\wc-demo\native\target\debug\deps -L dependency=C:\local_projects\rust\wc-demo\native\target\debug\deps --extern rand=C:\local_projects\rust\wc-demo\native\target\debug\deps\librand-340832a8942cb900.rlib --cap-lints allow`
Build failed, waiting for other jobs to finish...
failed to run custom build command for `neon-sys v0.1.7`
Process didn't exit successfully: `C:\local_projects\rust\wc-demo\native\target\debug\build\neon-sys-51e0087a6aa7f0e4\build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'failed to run "npm install" for neon-sys', ../src/libcore\option.rs:335
```

It seems like it's getting stucked here https://github.com/rustbridge/neon/blob/master/crates/neon-sys/build.rs#L21

**Comment by andruhon** [comment]
I've tried to handle the output rather than just assessing that `npm install` is not failed and figured out that rust can't find command `npm`, replacing "npm" to "npm.cmd" in build.rs helps, however it now choking on `Command::new("npm.cmd").arg("run").arg(if debug() { "build-debug" } else { "build-release" }).status().ok().unwrap();`. It seems like it can't find `ar` (trying to find one for windows)

```
> @ build-debug C:\local_projects\rust\wc-demo\native\crates\neon\crates\neon-sys
> node-gyp build -d


C:\local_projects\rust\wc-demo\native\crates\neon\crates\neon-sys>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build -d )  else (node  build -d )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  neon.cc
  win_delay_load_hook.c
  neon.vcxproj -> C:\local_projects\rust\wc-demo\native\crates\neon\crates\neon-sys\build\Debug\\neon.node
npm done
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
AR_x86_64-pc-windows-gnu = None
AR_x86_64_pc_windows_gnu = None
HOST_AR = None
AR = None
TARGET = Some("x86_64-pc-windows-gnu")
running: "ar" "crus" "C:\\local_projects\\rust\\wc-demo\\native\\crates\\neon\\crates\\neon-sys\\target\\debug\\build\\neon-sys-0c837cef5759fa85\\out\\libneon.a" "build/Debug/obj.target/neon/src/neon.o"


failed to execute command: The system cannot find the file specified. (os error 2)
Is `ar` not installed? (see https://github.com/alexcrichton/gcc-rs#compile-time-requirements for help)



--- stderr
npm WARN EPACKAGEJSON neon-sys No description
npm WARN EPACKAGEJSON neon-sys No repository field.
npm WARN EPACKAGEJSON neon-sys No license field.
thread '<main>' panicked at 'explicit panic', C:\multirust\cargo\registry\src\github.com-88ac128001ac3a9a\gcc-0.3.21\src\lib.rs:772
```

(I'm not sure now how did I get the original "file too long" message)

**Comment by andruhon** [comment]
Installed gcc for msys2 via packman, now having this:

```
...
C:\local_projects\rust\wc-demo\native\crates\neon\crates\neon-sys>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build -d )  else (node  build -d )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  neon.cc
  win_delay_load_hook.c
  neon.vcxproj -> C:\local_projects\rust\wc-demo\native\crates\neon\crates\neon-sys\build\Debug\\neon.node
npm done
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
AR_x86_64-pc-windows-gnu = None
AR_x86_64_pc_windows_gnu = None
HOST_AR = None
AR = None
TARGET = Some("x86_64-pc-windows-gnu")
running: "ar" "crus" "C:\\local_projects\\rust\\wc-demo\\native\\crates\\neon\\crates\\neon-sys\\target\\debug\\build\\neon-sys-0c837cef5759fa85\\out\\libneon.a" "build/Debug/obj.target/neon/src/neon.o"
ExitStatus(ExitStatus(1))


command did not execute successfully, got: exit code: 1



--- stderr
npm WARN EPACKAGEJSON neon-sys No description
npm WARN EPACKAGEJSON neon-sys No repository field.
npm WARN EPACKAGEJSON neon-sys No license field.
ar: build/Debug/obj.target/neon/src/neon.o: No such file or directory
thread '<main>' panicked at 'explicit panic', C:\multirust\cargo\registry\src\github.com-88ac128001ac3a9a\gcc-0.3.21\src\lib.rs:772
```

Will try to compile with msvc toolchain...

**Comment by andruhon** [comment]
cannot open input file 'build/Debug/obj.target/neon/src/neon.o' with i686-pc-windows-msvc

```
...
     Running `C:\local_projects\rust\wc-demo\native\crates\neon\crates\neon-sys\target\debug\build\neon-sys-7c321901adf440e6\build-script-build`
failed to run custom build command for `neon-sys v0.1.7 (file:///C:/local_projects/rust/wc-demo/native/crates/neon/crates/neon-sys)`
Process didn't exit successfully: `C:\local_projects\rust\wc-demo\native\crates\neon\crates\neon-sys\target\debug\build\neon-sys-7c321901adf440e6\build-script-build` (exit code: 255)
--- stdout
npm pretends
TARGET = Some("i686-pc-windows-msvc")
running: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\lib.exe" "/OUT:C:\\local_projects\\rust\\wc-demo\\native\\crates\\neon\\crates\\neon-sys\\target\\debug\\build\\neon-sys-7c321901adf440e6\\out\\libneon.a" "/nologo" "build/Debug/obj.target/neon/src/neon.o"
LINK : fatal error LNK1181: cannot open input file 'build/Debug/obj.target/neon/src/neon.o'
ExitStatus(ExitStatus(1181))


command did not execute successfully, got: exit code: 1181



--- stderr
thread '<main>' panicked at 'explicit panic', C:\multirust\cargo\registry\src\github.com-48ad6e4054423464\gcc-0.3.21\src\lib.rs:772
```

**Comment by andruhon** [comment]
Ahh. I think it is unlikely to work with msvc https://github.com/rustbridge/neon/blob/0a60bb4d9dca594efe7f84834ba7ccd7a5481938/crates/neon-sys/build.rs#L35
am I right?

**Comment by andruhon** [comment]
I've switched the multirust to gnu-nightly, it still can't find neon.o because node-gyp for windows using msvc. Not sure that I'm doing somewhat right, but I changed the
`format!("build/{}/obj/{}/src/{}.obj", mode(), libname, libname)`
to something like
```format!("C:\MY_ABSOUTE_PATH\build\{}\obj\{}\{}.obj", mode(),  libname, libname)

It now builds with `cargo build`,  however `neon build` crashing with 

```
Compiling wc-demo v0.1.2 (file:///C:/local_projects/rust/wc-demo/native)
src\lib.rs:72:26: 72:32 error: no method named `data` found for type `neon::internal::mem::Handle<'_, neon::internal::js::JsString>` in the current scope
src\lib.rs:72     let search = &string.data()[..];
                                       ^~~~~~
error: aborting due to previous error
Could not compile `wc-demo`.

To learn more, run the command again with --verbose.
neon ERR! cargo build failed
```

Well, I'm giving up for now. I don't have enough expertise about building C projects.
